export const palateProfile = {
    "version": 1,
    "profileName": "Chris red wine palate profile",
    "objective": "Assess likely personal enjoyment only. Do not optimise for critic score, prestige, value, investment potential, typicity or educational interest.",
    "summary": "Chris is primarily a pleasure and texture-driven red wine drinker. He most enjoys wines with ripe expressive fruit, velvety or silky mouthfeel, generous mid-palate, integrated oak or secondary complexity, integrated alcohol, and a long pleasurable finish. He dislikes wines where fruit fades and structure, alcohol, bitterness, greenness, savouriness, or drying tannin dominate. He admires precision and classicism, but the highest enjoyment comes from wines that feel sensual, complete, balanced and emotionally satisfying.",
    "coreEnjoymentDrivers": [
        "ripe expressive fruit",
        "velvety, silky, creamy or plush texture",
        "generous mid-palate",
        "fruit persistence through the finish",
        "integrated alcohol",
        "integrated oak",
        "sweet oak, cedar, tobacco, vanilla or baking spice complexity",
        "long evolving pleasurable finish",
        "harmony from attack to finish"
    ],
    "positiveDescriptors": [
        "ripe",
        "generous",
        "fruit-forward",
        "dark fruit",
        "blackcurrant",
        "blackberry",
        "plum",
        "black cherry",
        "bramble",
        "velvety",
        "silky",
        "creamy",
        "plush",
        "supple",
        "fleshy",
        "polished",
        "opulent",
        "balanced",
        "integrated",
        "long finish",
        "sweet oak",
        "vanilla",
        "cedar",
        "sweet tobacco",
        "cigar box",
        "baking spice",
        "clove",
        "mocha or chocolate when balanced"
    ],
    "negativeDescriptors": [
        "green",
        "vegetal",
        "herbaceous",
        "stalky",
        "underripe",
        "lean",
        "austere",
        "watery",
        "thin",
        "angular",
        "constrained fruit",
        "fruit fades quickly",
        "drying tannins",
        "dusty tannins",
        "chalky tannins",
        "hard tannins",
        "hot alcohol",
        "boozy",
        "over-extracted",
        "jammy without balance",
        "oxidative",
        "raisined",
        "medicinal",
        "dominant smoke",
        "dominant minerality",
        "savoury-dominant",
        "funk",
        "brett"
    ],
    "contextRules": {
        "overallGoal": "Prioritise likely enjoyment after reasonable aeration and at appropriate serving temperature, not the first few minutes after opening.",
        "fruit": "Ripe fruit is positive, especially when it persists beyond the attack. A wine with good initial fruit but a hollow mid-palate or finish should be downgraded.",
        "texture": "Texture is a primary driver. Velvety, silky, creamy or plush textures are strong positives. Thin, watery, gritty, dusty or drying textures are strong negatives.",
        "finish": "Length is positive only if the finish remains pleasurable. A long finish dominated by alcohol, savouriness, bitterness, or drying tannin is negative.",
        "oak": "Chris likes sweetness and polish from oak: vanilla, cedar, sweet tobacco, cigar box and baking spice. He dislikes heavy char, bitter coffee, heavy toast or smoke-dominant oak.",
        "tannin": "Firm tannin can be positive when ripe and integrated. Tannin becomes negative when it dominates flavour, dries the mouth or prevents enjoyment of the fruit.",
        "alcohol": "High alcohol is acceptable only when seamless. Any visible heat, booziness or alcohol dominance is a major caution.",
        "acidity": "Fresh acidity can be enjoyable in lighter juicy reds. In fuller-bodied serious reds, acidity should support fruit rather than dominate or make the wine feel sharp.",
        "minerality": "Minerality, graphite or pencil lead are acceptable as supporting complexity, especially in Bordeaux, but is negative if it suppresses fruit or dominates the finish.",
        "smoke": "Smoke is acceptable if subtle and integrated. Medicinal, saline or dominant smoke is negative.",
        "complexity": "Chris enjoys complexity, even with slight rough edges, if pleasure and balance remain intact. Complexity alone does not compensate for poor texture or finish."
    },
    "preferredStyleSignals": [
        "Ripe polished Bordeaux-style blends",
        "Plush Merlot-led wines",
        "Saint-Emilion, Pomerol or Lalande-de-Pomerol when ripe and polished",
        "Saint-Julien or modern Pauillac in ripe vintages",
        "Napa Cabernet Sauvignon, Merlot or Bordeaux blends when ripe, polished and balanced",
        "Bolgheri and polished Super Tuscans",
        "Ribera del Duero with dark fruit and creamy tannins",
        "Modern polished Rioja with sweet oak",
        "Modern polished Brunello or Sangiovese",
        "Washington State Cabernet or Bordeaux blends when plush and polished",
        "South African Cabernet or Bordeaux blends when plush and polished",
        "Fresh juicy low-tannin reds when fruit is vivid and clean"
    ],
    "explorationStyleSignals": [
        "Priorat if dark-fruited and polished rather than alcohol or slate-dominated",
        "Uco Valley or Mendoza Malbec if vivid, textural and not mineral-dominant",
        "richer ripe Burgundy if silky and sufficiently concentrated"
    ],
    "riskStyleSignals": [
        "cool-vintage Left Bank Bordeaux",
        "traditional Barolo or Barbaresco",
        "oxidative Rioja",
        "lean or mineral Burgundy",
        "funky natural wine",
        "Amarone or appassimento reds",
        "herbal Northern Rhone Syrah",
        "overblown hot New World reds"
    ],
    "vintageGuide": {
        "rule": "Warm or ripe vintages are generally most positive if alcohol remains integrated. Cool vintages are risky due to green notes, graphite dominance, constrained fruit and watery mid-palate."
    },
    "calibrationExamples": {
        "strongPositive": [
            "Chateau Laroque 2022",
            "Chateau Canon 2010/2016/2017",
            "Chateau Beau-Sejour Becot 2019/2020/2022",
            "Chateau Leoville Poyferre 2018",
            "Chateau Leoville Barton 2016",
            "Chateau Lynch-Bages 2009",
            "Chateau Margaux 2007",
            "Guado al Tasso 2018",
            "Alion 2016",
            "Calicem 2018",
            "Jessup Cellars Table for Four 2014/2015",
            "Cakebread Dancing Bear Ranch 2017",
            "Silver Oak Napa 2007",
            "Rutherford Ranch Reserve 2012",
            "Stag's Leap ARTEMIS 2016/2019",
            "G.D. Vajra Barbera d'Alba 2024"
        ],
        "cautionOrNegative": [
            "Clos du Marquis 2021: green, pencil lead, watery, constrained fruit",
            "Troplong Mondot 2017: dried herbs, bitterness, savoury dominance",
            "Chateau Palmer 2009 bottle experience: great nose and attack but fruit faded, alcohol and dusty tannin dominated",
            "Lopez de Heredia Tondonia: too oxidative and savoury",
            "Orin Swift style reds: too sweet, hot or over-extracted",
            "Traditional Barolo: tannin dominates enjoyment",
            "Amarone: often too raisined or sweet for a dry red"
        ]
    },
    "fitGuidance": {
        "strong": "Several signals converge strongly: ripe fruit, plush or silky texture, good mid-palate, integrated oak/alcohol/tannin, and likely pleasurable finish.",
        "good": "Likely enjoyable with mostly positive alignment, but may lack one major ideal feature such as depth, finish length or texture.",
        "maybe": "Mixed signals, limited evidence, or style has both attractive and risky traits for Chris.",
        "poor": "Likely dominated by known negatives such as greenness, austerity, watery texture, drying tannin, savouriness, oxidation, heat, or fruit fading before the finish."
    },
    "highlightGuidance": {
        "highlightTrueWhen": "Use highlight=true only for strong fit with medium_high or high confidence, or for an unusually compelling good fit with multiple converging positive signals.",
        "highlightFalseWhen": "Use highlight=false for maybe or poor fits, low confidence, or wines with major cautions even if quality appears high."
    },
    "reasoningGuidance": {
        "doNotOverweightRegion": "Region is only a clue. Prioritise inferred style: fruit persistence, texture, integration and finish quality.",
        "doNotOverweightPrestige": "Famous, expensive or critically acclaimed wines may still be poor fits if likely austere, green, drying, smoky, oxidative or savoury-dominant.",
        "useGeneralKnowledgeCarefully": "Use general wine knowledge to infer likely style from region, grape, producer, vintage and alcohol, but mark these as inferred evidence or assumptions.",
        "descriptionLimit": "Retailer descriptions are useful but may be marketing-heavy. Treat them as evidence, not truth.",
        "confidenceRule": "High confidence requires multiple converging signals. Thin metadata, unknown producer style, conflicting evidence or reliance on assumptions should lower confidence.",
    }
}
